# Generated by Django 4.2.11 on 2024-03-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=4, verbose_name='Скидка%'),
        ),
    ]
